modify

diff --git a/.github/workflows/check_database.yml b/.github/workflows/check_database.yml
--- a/.github/workflows/check_database.yml
+++ b/.github/workflows/check_database.yml
@@ -33,6 +33,10 @@ jobs:
         run: |
           CHECK_RESULT=$(python -c "from script.check import check_all; print(check_all('database'))")
           echo "CHECK_RESULT=$CHECK_RESULT"
+          if [ $CHECK_RESULT -ne 0 ]; then
+            echo "Error"
+            exit 1
+          fi
 
   check_hash:
     runs-on: ubuntu-latest
